version: "3"

services:
  frontend:
    container_name: vis_frontend
    hostname: vis_frontend
    build:
      context: ./frontend
    image: vis_frontend_image
    command: [ "npm", "run", "start" ]
    volumes:
      - ./frontend:/vis/frontend
      - /vis/frontend/node_modules
    working_dir: /vis/frontend
    ports:
      - "3000:3000"
    networks:
      visnet:
        ipv4_address: 175.0.0.3

  backend:
    container_name: vis_backend
    hostname: vis_backend
    build:
      context: ./backend
    image: vis_backend_image
    command: [ "npm", "run", "dev" ]
    volumes:
      - ./backend:/vis/backend
      - /vis/backend/node_modules
    working_dir: /vis/backend
    ports:
      - "3001:3001"
    networks:
      visnet:
        ipv4_address: 175.0.0.4

networks:
  visnet:
    driver: bridge
    ipam:
      config:
        - subnet: 175.0.0.0/16
